In [269]:
# Regresión Bosques Aleatorios

# Cómo importar las librerías
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [270]:
dataset = pd.read_excel('./Material/Datasets/Modelo 1.xlsx',sheet_name='Sheet3')

In [271]:
dummy_variables1 = pd.get_dummies(dataset['Plant'])
dummy_variables2 = pd.get_dummies(dataset['Route'])
dummy_variables3 = pd.get_dummies(dataset['Sold To Name'])
dummy_variables4 = pd.get_dummies(dataset['BU'])

In [272]:
dummy_variables4

0  Accesories  Business PC Solutions (BPS)  Large Format  \
0     0           0                            0             0   
1     0           0                            0             0   
2     0           0                            0             0   
3     0           0                            0             0   
4     0           0                            0             0   
...  ..         ...                          ...           ...   
1488  0           0                            0             0   
1489  0           0                            0             0   
1490  0           0                            0             0   
1491  0           0                            0             0   
1492  0           0                            0             0   

      Office Printing Solutions (OPS)  Supplies  
0                                   0         1  
1                                   0         1  
2                                   0         1  
3                                   1         0  
4                                   1         0  
...                               ...       ...  
1488                                0         1  
1489                                0         1  
1490                                0         1  
1491                                0         1  
1492                                0         1  

[1493 rows x 6 columns]

In [273]:
dataset = pd.concat([dataset, dummy_variables1,dummy_variables2,dummy_variables3,dummy_variables4], axis=1)

In [274]:
dataset['time']=dataset['tiempo de entrega']

In [275]:
dataset.drop(['Plant','Sold To Name','Route','tiempo de entrega','BU'],inplace=True,axis=1)

In [276]:
dataset.shape

(1493, 70)

In [277]:
X = dataset.iloc[:, 1:69].values
y = dataset.iloc[:, 69].values

In [278]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [279]:
X

array([[2.00000000e+01, 5.63160000e+03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.00000000e+00, 4.42840000e+02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.00000000e+00, 1.10810000e+03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       ...,
       [1.30000000e+02, 1.54604271e+04, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.55000000e+02, 3.63349500e+04, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.80000000e+02, 4.80536645e+04, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [280]:
dataset

Delivery  Actual Quant Delvrd  Net value USD  US21  US22  US23  US27  \
0     8028333983                   20    5631.600000     0     0     1     0   
1     8028409605                    2     442.840000     0     0     1     0   
2     8028063213                    2    1108.100000     0     0     1     0   
3     8028080883                    1    3822.500000     0     1     0     0   
4     8028098914                   30  144324.880000     0     1     0     0   
...          ...                  ...            ...   ...   ...   ...   ...   
1488  8027581970                  420    7670.075368     0     0     0     0   
1489  8027601541                   60    1054.805684     0     0     0     0   
1490  8027601613                  130   15460.427074     0     0     0     0   
1491  8027657008                  255   36334.950000     0     0     0     0   
1492  8027818086                  180   48053.664537     0     0     0     0   

      US38  4U10CO  4U11CO  ...  UNIVERSIDAD DE LA SABANA  VENEPLAST LTDA  \
0        0       0       0  ...                         0               0   
1        0       0       0  ...                         0               0   
2        0       0       0  ...                         0               0   
3        0       0       0  ...                         0               0   
4        0       0       0  ...                         0               0   
...    ...     ...     ...  ...                       ...             ...   
1488     1       0       0  ...                         0               0   
1489     1       0       0  ...                         0               0   
1490     1       0       0  ...                         0               0   
1491     1       0       0  ...                         0               0   
1492     1       0       0  ...                         0               0   

      ZOFICOL SAS  0  Accesories  Business PC Solutions (BPS)  Large Format  \
0               0  0           0                            0             0   
1               0  0           0                            0             0   
2               0  0           0                            0             0   
3               0  0           0                            0             0   
4               0  0           0                            0             0   
...           ... ..         ...                          ...           ...   
1488            0  0           0                            0             0   
1489            0  0           0                            0             0   
1490            0  0           0                            0             0   
1491            0  0           0                            0             0   
1492            0  0           0                            0             0   

      Office Printing Solutions (OPS)  Supplies  time  
0                                   0         1    18  
1                                   0         1    16  
2                                   0         1    24  
3                                   1         0    75  
4                                   1         0    29  
...                               ...       ...   ...  
1488                                0         1     7  
1489                                0         1     7  
1490                                0         1     7  
1491                                0         1     6  
1492                                0         1     6  

[1493 rows x 70 columns]

In [281]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [282]:
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(n_estimators = 2000, random_state=42)
regression.fit(X_train,y_train)

RandomForestRegressor(n_estimators=2000, random_state=42)

In [283]:
y_train

array([36, 34, 21, ..., 17, 10, 12], dtype=int64)

In [284]:
y_predi = regression.predict(X_test)

In [285]:
y_predi

array([67.38718452, 15.1915    , 29.55316667, 21.94388333, 20.3935    ,
       14.26363929, 38.50566667, 70.97032381, 34.28575   , 14.69714139,
       18.098525  , 32.39131667, 14.95      , 42.98550734, 59.91871667,
       31.36583333, 15.26875   , 13.2743    , 12.21227857, 17.67762024,
       32.19879167, 32.21616667, 22.0095    , 20.7665    , 12.95238333,
       26.78766667, 13.81833333, 18.02476667, 13.99458333, 15.63430476,
       35.2825    , 20.36791667, 62.24569643, 24.74987143, 29.1515    ,
       27.92778333, 17.713     , 28.71175   , 30.0495    , 21.87666667,
       12.23996548, 33.79831786, 23.40725   , 19.143     , 16.87630532,
       29.55316667, 11.34241667, 11.4295    ,  9.90049524, 19.89343452,
       31.96421071, 35.33241667, 14.33907976, 10.981     , 13.32765714,
       22.3415    , 21.0205    , 11.2855    , 16.63694881, 16.50618214,
       11.1925    , 20.202     , 12.30116667, 47.788375  , 18.1235    ,
       11.90589048, 10.49325   , 19.42913095, 20.9165    , 21.70

In [286]:
from sklearn.metrics import r2_score
# obtener predicciones para el conjunto de prueba
y_pred = regression.predict(X_test)
# calcular R2
r2 = r2_score(y_test, y_pred)
print('R2:', r2)


R2: 0.7093184735746574


In [287]:
from sklearn.metrics import mean_squared_error

# obtener predicciones para el conjunto de prueba
y_pred = regression.predict(X_test)

# calcular MSE
mse = mean_squared_error(y_test, y_pred)

print('MSE:', mse)

MSE: 103.6163224081782


In [288]:
dataset.to_excel('p.xlsx',index=False)

In [ ]:
df = pd.DataFrame(y_predi, columns=['Columna 1'])
df2 = pd.DataFrame(y_test)

In [ ]:
df.to_excel('k.xlsx')
df2.to_excel('f.xlsx')